# Generated by Django 5.0.6 on 2024-06-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_continet_code_continet_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Continet',
        ),
    ]
