# Generated by Django 5.0.6 on 2024-06-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_continet_body_alter_continet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='continet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
