# Generated by Django 5.0.6 on 2024-06-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_continet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continet',
            name='image',
        ),
    ]
