# Generated by Django 5.0.6 on 2024-06-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_continet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continet',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
