# Generated by Django 5.0.6 on 2024-06-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_continet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='continet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
